[project]
name = "buffaloner-github-io"
version = "0.1.0"
description = "Buffaloner.ME - personal site for The Buffaloner"
readme = "README.md"
authors = [
    { name = "The Buffaloner", email = "168052884+buffaloner@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.7.7",
    "properdocs>=1.6.7",
    "pymdown-extensions>=11.0.1",
]

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"
