[input]
url_prefix = ""
base_directory = "content"
html_selector = "main"

[[input.files]]
path = "articles/04_life_without_shame.md"
url = "/posts/2024/May/28/life-without-shame/"
title = "Life Without Shame"

[[input.files]]
path = "articles/03_long_live_the_rebellion.md"
url = "/posts/2024/May/22/long-live-the-rebellion/"
title = "Long Live the Rebellion"

[[input.files]]
path = "articles/02_asmr.md"
url = "/posts/2024/May/19/asmr/"
title = "Anti Social Media Rebellion"

[[input.files]]
path = "articles/01_soft_opening.md"
url = "/posts/2024/May/06/soft-opening/"
title = "Soft Opening"
